import type { Metadata } from "next";
import {Rethink_Sans } from "next/font/google";


const Inter = Rethink_Sans({
  subsets: ["latin"],
  display:"swap",
});

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${Inter.className} ${Inter.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
